# NUMPY

Numpy is a python module that is used for scientfic computing and is 50x times faster than Lists.

NumPy stands for numerical python.

Numpy contains high-dimensional array objects,tools for dealing whit array objects.

It also helps in dealing with linear algebra,fourier transform and has random number capabilities.

Numpy aims to provide an array object called as ndarray.

These arayrs are stored at continuous place in memory unlike list,this behaviour is called locality of reference.

Numpy can also be treated as container for generic data.

Numpy is partially written in python,and partialy in C and C++ for faster computation.

Numpy only deals with numerical values.

In [14]:
#installing numpy-in ditstribution like Annaconda and spyder it is already available.

pip install numpy

In [ ]:
#to check for version
print(np.__version__)

In [27]:
#importing numpy
import numpy as np  #np is an alias name commonly used for numpy


Advantages of numpy over list: 
    
    1.Occupies less memory
    
    2.Fast
    
    3.Convinient

In [33]:
#code that shows numpy occupies less m/m space thean lists
import numpy as np
import time
import sys
S=range(1000)
print("List m/m: ",sys.getsizeof(S)*len(S))

D=np.arange(1000)
print("Numpy object m/m: ",D.size*D.itemsize)

#following result shows the space occupied

List m/m:  48000
Numpy object m/m:  4000


In [36]:
#code that shows how numpy is faster than lists
import numpy as np
import time
import sys
SIZE=1000

#two lists are defined
L1=range(SIZE)
L2=range(SIZE)

#two numpy arrays
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=[(x,y) for x,y in zip(L1,L2)] #sums corresponding element
print("Lists: ",(time.time()-start)*1000) #converting into milliseconds

start=time.time()
result=A1+A2 #numpy array elements are automatically corespondedly added
print("Numpy array: ",(time.time()-start)*1000) 

Lists:  1.0123252868652344
Numpy array:  0.0


NUMPY OPERATIONS

In [11]:
#creating an array

#array() function a ndarray object array-- we can pass list as well as tuple in array() function
ar1=np.array([1,2,3]) 
print(ar1)

[1 2 3]


In [22]:
#for creating 2D-dimensional array here we are using tuples
ar2=np.array(((1,2,3),(4,5,6)))
print(ar2)

[[1 2 3]
 [4 5 6]]


In [43]:
#for creating 2D-dimensional array here we are using lists
ar3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
#creating a 3D array: 
ar4=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar4)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [66]:
#creating a high dimensional numpy array
ar5= np.array([1, 2, 3, 4], ndmin=5)
#here 5-D we can put different value

In [67]:
print(type(ar1))
print(type(ar2))
print(type(ar3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [68]:
#to check the dimension of numpy array: 
print(ar1.ndim)
print(ar2.ndim)
print(ar3.ndim)
print(ar4.ndim)

1
2
2
3


In [69]:
#to check sie of each element present in numpy array: 
print(ar1.itemsize)

4


In [70]:
#to check datatype of elements inside numpy array: 
print(ar2.dtype)
print(ar4.dtype)

int32
int32


In [71]:
#to check the size of the array(total number of elements)
print(ar1.size)
print(ar2.size)
print(ar3.size)
print(ar4.size)

3
6
9
12


In [72]:
#to check shape of the numpy array: 
print(ar1.shape)
print(ar2.shape)
print(ar3.shape)
print(ar4.shape)

(3,)
(2, 3)
(3, 3)
(2, 2, 3)


In [73]:
#properties of 5D array:
print(ar5.shape)
print(ar5.ndim)

(1, 1, 1, 1, 4)
5


In [79]:
#reshaping a numpy array(not permanent)
print(ar2)
print(ar2.reshape(3,2))
#on reshaping new dimension values should result to same previous size

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#slicing in numpy array: 